### PR TITLE
Add annotation for cluster auto scaler eviction

### PR DESCRIPTION
**Pull request by pipo02mix**
It only marks the pod to be eligible for eviction when a cluster auto-scaler is running otherwise all nodes with ingress controller cannot be touched. https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node

### CODE REVIEW

**Comment by pipo02mix** [comment]
done https://github.com/giantswarm/kubernetes-nginx-ingress-controller/pull/69

**Comment by pipo02mix** [comment]
> also should we add pod disruption budget once we allow eviction?

**Comment by indyfree** [comment]
FYI if you don't increase the minor version changes get rolled automatically. See https://github.com/giantswarm/kubernetes-kube-state-metrics/pull/32#issuecomment-436176336.

**Comment by pipo02mix** [comment]
I think it this case would be ideal, don't you think?

**Comment by indyfree** [comment]
> I think it this case would be ideal, don't you think?

Yes sure, I am not deep into IC changes, just wanted to make you aware :)

**Comment by pipo02mix** [comment]
IMO since the version is the same and there is any significant change push in the same channel would be great. So we don't need to wrap it in cluster operator and make a new deployment

@puja WDYT? approve?

**Review by puja108 — APPROVED** [review]

**Pull request merged**
