### PR TITLE
Add log format upstream config parameter

### PR DESCRIPTION
**Pull request by pipo02mix**
Towards https://github.com/giantswarm/giantswarm/issues/5028

### CODE REVIEW

**Review by rossf7 — APPROVED** [review]
LGTM

**Comment by oponder** [comment]
Does this just get deployed and work automatically for our tenant clusters? Does something need to be restarted?

**Comment by pipo02mix** [comment]
Yeah the problem I have observed it is the values are parsed from `nginx-ingress-controller-user-values` to `ingress-nginx` when the chart is deployed/upgraded. So if customer add parameters later, we need to copy then to the original config map. @puja108 maybe it would be nice to implement a feature that checks if the content has changed in every reconcialiation loop, WDYT?

**Comment by puja108** [comment]
@rossf7 not sure how trivial that would be ^

In general I would not put too much time into it as we will move the user config to control plane at some point hopefully soonish

**Comment by rossf7** [comment]
This seems strange and maybe a bug with the merge logic. The values shouldn't need to be in the values configmap. The logic should just be that user values override the values configmap if the same key is present in both.

But I agree I don't think we should invest lots of time here. This all gets replaced by the app CRD. It's better to spend time on getting that right.

**Pull request merged**
