### PR TITLE
Add use-forwarded-for to default

### PR DESCRIPTION
**Pull request by jgsqware**
Signed-off-by: Julien Garcia Gonzalez <julien@giantswarm.io>

@rossf7 is this enough for setting the default value and let the user modifying if needed?

### CODE REVIEW

**Comment by pipo02mix** [comment]
Yes it should be, but you can test it first

**Comment by jgsqware** [comment]
@pipo02mix how I test the PR?

**Comment by pipo02mix** [comment]
You can use this  [script](https://github.com/giantswarm/giantswarm/blob/1bc2289a72811e503996dc0f8ee6e179649f7d7f/support/scripts/deploy-service.sh)
Basically it changes the chart CR to use the WIP generated by CI

**Comment by jgsqware** [comment]
ok tested and it works

**Pull request merged**
