### PR TITLE
Add http backend migrator chart

### PR DESCRIPTION
**Pull request by pipo02mix**
towards https://github.com/giantswarm/giantswarm/issues/4825#issuecomment-447372587

Created a dependency chart like a migrator resources that delete the default httpbackend service before the upgrade so the nginx controller upgrade install the new one even if the service type has changed

### CODE REVIEW

**Review by rossf7 — APPROVED** [review]
LGTM. Just needs the chart version bump for deployment.

**Comment by indyfree** [comment]
/cc @rossf7 The patch version bump is not needed anymore, because we added the `[[.SHA]]` to the version again. We had an issue where the pushing without incrementing could affect already deployed charts. See here: https://github.com/giantswarm/giantswarm/issues/4441
The only reason the patch version is still in there is because architect looks for a valid SemVer and we are moving away from it anyways

/cc @pipo02mix I see `push_to_stable` failed (probably because quay is down) you should run CI again when quay is back again, to have it in the channel (to deploy).

**Comment by pipo02mix** [comment]
yeah second time it succeded ;)

**Comment by rossf7** [comment]
@indyfree That's great news and I'd totally missed it somehow! Thx for the info <3

**Pull request merged**
