### PR TITLE
Use e2esetup library

### PR DESCRIPTION
**Pull request by rossf7**
Towards https://github.com/giantswarm/giantswarm/issues/4076

Uses e2esetup for wiring the managed service and migration tests. See https://github.com/giantswarm/e2esetup/pull/3 for the lib changes.

### CODE REVIEW

**Review by fgimenez — APPROVED** [review]
Nice, LGTM (g standing for great)

**Review by xh3b4sd — COMMENTED** [review]
Same feedback as in the `aws-operator` PR. Good direction though. Really nice. <3

**Review by rossf7 — COMMENTED** [review]
Wiring is updated. @xh3b4sd @kopiczko PTAL 

I'll make the same changes in aws-operator.

**Review by xh3b4sd — APPROVED** [review]
Nice.

**Pull request merged**
